### ISSUE TITLE
/hqm load all HQM New Heights - 5.0.0beta4

### ISSUE THREAD

**Issue by chris-gauth** [lorddusk/HQM#231]
I cannot for the life of me get my self made HQM pack onto a server. In singleplayer I /hqm save (every quest set) can see all the .json files in the export folder.  I started a nodecraft server, all files match (from the /save file to config folder) have tried HQM config "server will send quest to client" true and false. Still get a blank quest book. 

I am the owner of the server
confirmed i am OP'd 
HQM still says "you not have permission to use this command" 
-tried in edit mode and non edit mode (both server and client)
-Open the quest book multiple times, still no joy. 
Cannot fine anything on the internet to help. 
added my export file from my singleplayer

**Comment by lorddusk** [comment]
Both Server and Client need the same .hqm file for the client to be able to
see quests.

On Sep 13, 2016 10:31 AM, "OneLargeFarva" notifications@github.com wrote:

I cannot for the life of me get my self made HQM pack onto a server. In
singleplayer I /hqm save (every quest set) can see all the .json files in
the export folder. I started a nodecraft server, all files match (from the
/save file to config folder) have tried HQM config "server will send quest
to client" true and false. Still get a blank quest book.

I am the owner of the server
confirmed i am OP'd
HQM still says "you not have permission to use this command"
-tried in edit mode and non edit mode (both server and client)
-Open the quest book multiple times, still no joy.
Cannot fine anything on the internet to help.
added my export file from my singleplayer

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/lorddusk/HQM/issues/231, or mute the thread

**Comment by chris-gauth** [comment]
There is no .hqm file for anything. But client and server match 100%

**Comment by chris-gauth** [comment]
Still having same issue. /hqm load all says "You not have permission to use this command" and this is doing it from my server (nodecraft) console. 

Even starting a fresh hqm (deleting all HQM files) it still says i dont have permissions for /hqm load all.

when i do /hqm save all i get this in the console:
An unknown error occurred while attempting to perform this command
Couldn't process command: 'hqm save all'
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.Collection
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
at com.google.gson.Gson.toJson(Gson.java:572) ~[Gson.class:?]
at hardcorequesting.io.SaveHandler.save(SaveHandler.java:294) ~[SaveHandler.class:?]
at hardcorequesting.commands.CommandSave.save(CommandSave.java:101) ~[CommandSave.class:?]
at hardcorequesting.commands.CommandSave.handleCommand(CommandSave.java:33) ~[CommandSave.class:?]
at hardcorequesting.commands.CommandHandler.func_184881_a(CommandHandler.java:80) ~[CommandHandler.class:?]
at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

/hqm load all
You not have permission to use this command

**Comment by jelaw21** [comment]
I am having the same issue. This would be with the new HQM version 1.9.4

**Comment by way2muchnoise** [comment]
You should just have to copy the hqm folder from you local SP world folder to the MP world folder

**Comment by jelaw21** [comment]
Tried that. No go. Was just playing around with /hqm save all (which
produced an unknown error) but it generated an export folder?

**Comment by jelaw21** [comment]
I copied the entire world folder from SP over into MP and no go.

**Comment by jelaw21** [comment]
Ok so, future messing around. The hqm config folder client side receives a folder called remote from the server, inside that folder is another remote folder and inside of that is all the quest files, the sets, the deaths, the reputations.

**Comment by chris-gauth** [comment]
Same here. However all combinations of files and folders still yield nothing. I am able to freely import sets between 2 sp world's but still no luck with a server.

**Comment by EverNife** [comment]
Same :/

**Comment by canitzp** [comment]
#249
