### ISSUE TITLE
[1.10.2] Awful FPS drop when Maximum retrieval count > 0

### ISSUE THREAD

**Issue by DV666** [lorddusk/HQM#263]
First english isn't my native language so... sorry ^^

I encounter a big issue while editing book : i am creating some reward bag and after some examples, when i want to open any reward bag, FPS drop drastically ! (120+ to 30 or 0 !)
After fews secondes and freezes, window didn't show after opening this bag and i get loots directly on my inventory...

That was working perfectly before but now... it's awful : i don't know why... I remove last reward bag i added but bug still persist.
Maybe the .json is corrupted, i must check that.

I paste the latest logs found on folder.

Version used : Hardcore Questing Mode - Version : 1.10.2-5.0.0beta4
Memory allocated : 6,144 Mb

> [19:46:19] [Client thread/INFO]: [CHAT] There is an Update for Actually Additions available!
[19:46:19] [Client thread/INFO]: [CHAT] Current Version: 1.10.2-r88, newest Version: 1.10.2-r97
[19:46:19] [Client thread/INFO]: [CHAT] [Click for Changelog] [Click for Download]
[19:46:38] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_25]
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137) ~[?:1.8.0_25]
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121) ~[?:1.8.0_25]
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:622) ~[?:1.8.0_25]
	at java.lang.StringBuffer.append(StringBuffer.java:383) ~[?:1.8.0_25]
	at java.io.StringWriter.write(StringWriter.java:77) ~[?:1.8.0_25]
	at java.io.StringWriter.append(StringWriter.java:202) ~[?:1.8.0_25]
	at java.io.StringWriter.append(StringWriter.java:41) ~[?:1.8.0_25]
	at com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:621) ~[JsonWriter.class:?]
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:478) ~[JsonWriter.class:?]
	at hardcorequesting.client.interfaces.GuiType$4.build(GuiType.java:96) ~[GuiType$4.class:?]
	at hardcorequesting.items.ItemBag.openClientInterface(ItemBag.java:121) ~[ItemBag.class:?]
	at hardcorequesting.items.ItemBag.func_77659_a(ItemBag.java:92) ~[ItemBag.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[19:46:38] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 15761ms behind, skipping 315 tick(s)
[19:46:49] [Client thread/INFO]: [CHAT] help, version, quest, hardcore, lives, edit, enable, save, load
[19:46:54] [Client thread/INFO]: [CHAT] §aHardcore Questing Mode - Version : 1.10.2-5.0.0beta4

>

**Comment by DV666** [comment]
I found it : when you change value on "Maximum retrieval count" another than 0, that will cause theses FPS drop.

Title edited.

**Comment by canitzp** [comment]
I can confirm this, but I don't know why it's happening.

**Comment by noobanidus** [comment]
@canitzp You added this to the 5.4.0 milestone. Is it still an issue?

**Comment by noobanidus** [comment]
I don't seem to be ale to reproduce this issue. The code itself was changed recently when @canitzp did a lot of work on packets. I'm going to close it for now. If it recurs it can be reported again, hopefully. I tried this with a couple of loot bags and a non-0 value and didn't have the issue.
