### ISSUE TITLE
[1.10.2] Opening quest bags in SMP causing enormous lag spikes

### ISSUE THREAD

**Issue by arfink** [lorddusk/HQM#318]
(using version 5.1.0alpha4 for 1.10.2 with Forge 1.10.2-12.18.3.2185)
When opening quest bags, I find that there will be a huge lag spike, which the system will eventually recover from, but not before spewing this error. Also, the reward from the bag will enter the player's inventory as long as they don't time out and disconnect, although the interface to display the reward info will not appear, and the bag is not consumed. AFAIK there should not be a RAM issue, I have 6gb allocated, which should be far more than enough.

`
[15:54:20] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_111]
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[?:1.8.0_111]
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649) ~[?:1.8.0_111]
        at java.lang.StringBuffer.append(StringBuffer.java:381) ~[?:1.8.0_111]
        at java.io.StringWriter.write(StringWriter.java:77) ~[?:1.8.0_111]
        at java.io.StringWriter.append(StringWriter.java:202) ~[?:1.8.0_111]
        at java.io.StringWriter.append(StringWriter.java:41) ~[?:1.8.0_111]
        at com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:621) ~[JsonWriter.class:?]
        at com.google.gson.stream.JsonWriter.value(JsonWriter.java:478) ~[JsonWriter.class:?]
        at hardcorequesting.client.interfaces.GuiType$4.build(GuiType.java:96) ~[GuiType$4.class:?]
        at hardcorequesting.items.ItemBag.openClientInterface(ItemBag.java:121) ~[ItemBag.class:?]
        at hardcorequesting.items.ItemBag.func_77659_a(ItemBag.java:71) ~[ItemBag.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
'

**Comment by arfink** [comment]
BTW, if I delete my bags.json file from /world and from /config/hqm/default then it will consume the bag without lagging out the server. My bags.json is attached.
[bags-json.txt](https://github.com/lorddusk/HQM/files/950002/bags-json.txt)

**Comment by arfink** [comment]
Found that making a reward have a limit value caused this issue. Removing the limits from quest bags fixed the issue.

**Comment by mindlessmrwaesome** [comment]
Oh my goodness thank you
I almost switched over to Better Questing after being stuck with this lag problem, which would have made me lose about 3 hours of work.
You just saved a good chunk of my life and I am grateful :D

**Comment by canitzp** [comment]
Thanks for not switching yet @mindlessmrwaesome :smiley:

**Comment by UltaVulta** [comment]
This error isn't fixed yet... I still have it

**Comment by canitzp** [comment]
@UltaVulta Can you test a mod version for me now, if I gave it to you? 1.12.2

**Comment by UltaVulta** [comment]
Yes

**Comment by canitzp** [comment]
here it is http://puu.sh/Bevq1/a6486e5481.jar

**Comment by canitzp** [comment]
@UltaVulta How long does it take before you can test it?

**Comment by UltaVulta** [comment]
Hey! Sorry, literally just tested. I was in the middle of something else and had to boot everyone off my server. There are no lag spikes but it caused my limits to be removed. I had it limited to 1 drop for each tier and now that's just been removed in that update.

Thanks, 
 - Ulta

**Comment by canitzp** [comment]
I'm a bit stupid, so can you just explain what limits are and what they should do?

**Comment by UltaVulta** [comment]
Hey, Sorry about being so slow,

Basically, it was something when creating loot bag rewards that let me set the number of rewards that were meant to be given each time a bag was opened. I set this to only 1 because the items in bags were op. What it has been doing is lagging the server out a lot then either crashing or giving every item despite the limitations. Now what it does is it doesn't give the lag spike or crash but still gives every item possible, just ignoring the limit.

Thanks,
 Ulta

**Comment by canitzp** [comment]
@UltaVulta You mean the retrival count that can be set for every group?

**Comment by UltaVulta** [comment]
Yes

**Comment by canitzp** [comment]
The retreval count doesn't say how much items of one group are in one bag, but how often the group can be received through a player. If you only want one item per bag than you need to create a lot of groups with just one item in them

**Comment by UltaVulta** [comment]
Oh... Welp now i feel dumb lol. Im so so so sorry for wasting so much time

**Comment by canitzp** [comment]
You don't wasted time. I learned it to and I should know it beforehand. Hava a good day
