### ISSUE TITLE
ArrayIndexOutOfBoundsException when crafting any item

### ISSUE THREAD

**Issue by HaydenBelanger** [lorddusk/HQM#348]
This bug prevents the user from taking out any material easily from the crafting bench or sometimes at all. I can't tell what is causing this issue.
Version is HQM-New Heights-1.10.2-5.0.0beta4.jar
```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 2
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at hardcorequesting.quests.task.QuestTaskItems.increaseItems(QuestTaskItems.java:311) ~[QuestTaskItems.class:?]
	at hardcorequesting.quests.task.QuestTaskItemsCrafting.create(QuestTaskItemsCrafting.java:45) ~[QuestTaskItemsCrafting.class:?]
	at hardcorequesting.quests.task.QuestTaskItemsCrafting.onCrafting(QuestTaskItemsCrafting.java:33) ~[QuestTaskItemsCrafting.class:?]
	at hardcorequesting.event.EventHandler.onEvent(EventHandler.java:79) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_669_EventHandler_onEvent_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:585) ~[FMLCommonHandler.class:?]
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:111) ~[acb.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:324) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by HaydenBelanger** [comment]
Never mind, confirmed working as normal as of the latest 1.10.2 alpha version.
