### ISSUE TITLE
World Crash when clicking on any quest.

### ISSUE THREAD

**Issue by Krhymez** [lorddusk/HQM#366]
I do not know what is causing this, but it seems once i reach a ceartain amount of quests it crashed. here is a pastebin. 
https://pastebin.com/3n5Z1Rt4

**Comment by royalcw** [comment]
Starting to experience the same issues myself.  Been building up a quest book and after making 80 some quests I get this error a lot.

**Comment by Boolyman** [comment]
We really need some responses to these issues... these are game breaking.

**Comment by Krhymez** [comment]
I dropped all quest mods for 1.12.2
May be the better option here.

**Comment by lorddusk** [comment]
I will start a complete rewrite this weekend.



Met vriendelijke groeten,

Tim Langen

**Comment by Bullorg74** [comment]
I guess I got this to. Got to about 80 quests then "world freeze" and I have to force close the game.

MC 1.12,2
Forge 14.23.2.2654 and 14.23.2.2652 same issue with both.
HQM 1.12.x-5.2.0Alpha1

Is there any timeline on a update?

I just really like this mod and I want to use it.
I really appriciate all the work you modders do.

[14:01:32] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel hcQuesting
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: The string is too long for this encoding.
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) ~[SimpleNetworkWrapper.class:?]
	at hardcorequesting.network.NetworkManager.sendToPlayer(NetworkManager.java:47) ~[NetworkManager.class:?]
	at hardcorequesting.quests.QuestLine.sendServerSync(QuestLine.java:86) ~[QuestLine.class:?]
	at hardcorequesting.event.PlayerTracker.onPlayerLogin(PlayerTracker.java:39) ~[PlayerTracker.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_832_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:574) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: The string is too long for this encoding.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.5.jar:3.5]
	at net.minecraftforge.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:166) ~[ByteBufUtils.class:?]
	at hardcorequesting.network.message.PlayerDataSyncMessage.toBytes(PlayerDataSyncMessage.java:53) ~[PlayerDataSyncMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:71) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:4.1.9.Final]
	... 27 more
[14:01:32] [Netty Server IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[14:01:32] [main/INFO] [journeymap]: Mapping halted in D:\Minecraft\Instances\Basic but fun 1,12,2\journeymap\data\sp\ore testing\DIM0
[14:01:32] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Bullorg74 lost connection: A fatal error has occurred, this connection is terminated
[14:01:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Bullorg74 left the game
[14:01:32] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Stopping singleplayer server as player logged out
[14:01:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[14:01:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[14:01:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[14:01:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'ore testing'/overworld
[14:01:32] [Server thread/INFO] [FML]: Unloading dimension 0
[14:01:34] [Server thread/INFO] [FML]: Applying holder lookups
[14:01:34] [Server thread/INFO] [FML]: Holder lookups applied

Or if there is anybody clever that can tell me what else I done wrong.

**Comment by canitzp** [comment]
This problem does came from the fact that you're having to many quest, so mc just can't send all of it within the bounds of one packet. This can't b fixed before the rewrite is finished
