### ISSUE TITLE
Crash when closing quest book with the ESC button

### ISSUE THREAD

**Issue by royalcw** [lorddusk/HQM#370]
Not sure how else to close the quest book other than hitting Esc key.  I've been building a quest series over the last few weeks and have about 70 quests or so built.  Today, the game randomly hit a fatal error and booted me out of the world when I tried to close the quest book and now crashes every time I close the book.  The only thing I did before this happened is a I added a new quest but didn't input anything into the new quest.  I then went back into the world, added items title and content to the quest and tried to close the book again and got the same error in the log.  I then deleted the new quest and still get the error in the log everytime I close the quest book.

Minecraft: 1.12.2
Forge: 14.23.0.2522 (can't use higher or get Extra Utils 2 crashes and this is a known issue for EU2)
HQM Version: 1.12.x-5.2.0Alpha1

<details>
  <summary>Click to see Error Log</summary>
[21:55:34] [Netty Server IO #3/ERROR]: There was a critical exception handling a packet on channel hcQuesting
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: The string is too long for this encoding.
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:249) ~[SimpleNetworkWrapper.class:?]
	at hardcorequesting.network.NetworkManager.sendToPlayer(NetworkManager.java:47) ~[NetworkManager.class:?]
	at hardcorequesting.quests.QuestLine.sendServerSync(QuestLine.java:86) ~[QuestLine.class:?]
	at hardcorequesting.event.PlayerTracker.onPlayerLogin(PlayerTracker.java:39) ~[PlayerTracker.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1393_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: The string is too long for this encoding.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[commons-lang3-3.5.jar:3.5]
	at net.minecraftforge.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:166) ~[ByteBufUtils.class:?]
	at hardcorequesting.network.message.PlayerDataSyncMessage.toBytes(PlayerDataSyncMessage.java:53) ~[PlayerDataSyncMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:4.1.9.Final]
	... 27 more
[21:55:34] [Netty Server IO #3/ERROR]: Network Disconnect: A fatal error has occurred, this connection is terminated
</details>

**Comment by royalcw** [comment]
Self corrected.  Updated my Forge since a new EU2 version came out.  Issue resolved.

**Comment by royalcw** [comment]
The issue stopped for a couple days after updating to Forge 14.23.0.2542 and I was able to build 15 more quests or so.  The same issue has returned.  The game crashes to the server select page (playing on local computer only) every time I close my quest book.  The log is the same as the original posted above.

**Comment by Boolyman** [comment]
Im getting this issue too now.

**Comment by lorddusk** [comment]
We are planning a complete rewrite very soon.

**Comment by TheQKnight** [comment]
I am now getting this issue as well. This mod has not been updated since October. Can you please update this mod to fix some of the bugs? I have had so many issues that it is almost impossible to play.

**Comment by canitzp** [comment]
Should be fixed since 5.3.0
