### ISSUE TITLE
Creating reputation causes crash on world loading and startup

### ISSUE THREAD

**Issue by yelldow** [lorddusk/HQM#530]
Replication:
Works on empty Fabric install (MC 1.16.4, Fabric 0.10.8, Cloth API 1.4.9, Fabric API 0.28.4, HQM 5.5.4)
Create a new world, then go into creative and give yourself a questbook. Type /hqm edit, then proceed to create a reputation. For my crash, I created 6 tiers, but I'm unsure how that affects the crash.
Save all, close the world, then try to create a new one - you should crash. Any subsequent launches should also crash.

<details>
  <summary>Startup Crashlog</summary>

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hardcorequesting'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.ClassCastException: hardcorequesting.common.fabric.bag.GroupTier cannot be cast to hardcorequesting.common.fabric.reputation.Reputation
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at hardcorequesting.common.fabric.reputation.ReputationManager.lambda$loadFromString$1(ReputationManager.java:65)
	at java.util.Optional.ifPresent(Optional.java:159)
	at hardcorequesting.common.fabric.reputation.ReputationManager.loadFromString(ReputationManager.java:65)
	at java.util.Optional.ifPresent(Optional.java:159)
	at hardcorequesting.common.fabric.quests.SimpleSerializable.load(SimpleSerializable.java:36)
	at hardcorequesting.common.fabric.quests.QuestLine.loadAll(QuestLine.java:185)
	at hardcorequesting.common.fabric.HardcoreQuestingCore.initialize(HardcoreQuestingCore.java:57)
	at hardcorequesting.fabric.HardcoreQuestingFabric.onInitialize(HardcoreQuestingFabric.java:81)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

</details>

**Comment by ghost** [comment]
I have a similar issue, except it crashes when the game loads rather than the world, :(
and I'm on forge 
https://pastebin.com/2Fe9NuR7

**Comment by ghost** [comment]
It seems to have something to do with Reward Bags or Groupings of Reward bags - of which I have 0 reward bags/tiers - @yelldow , did your questing setup have any reward bags or tiers of them?

**Comment by kirderf1** [comment]
Considering the error in the crashlog, this issue should be fixed with #527 (HQM 5.5.5)

**Comment by canitzp** [comment]
If you say so, then I close it
