### ISSUE TITLE
[Fabric] server crash on startup

### ISSUE THREAD

**Issue by MSandro** [lorddusk/HQM#566]
HQM-1.16.4+5.5.8-fabric
fabric-api-0.35.0+1.16
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hardcorequesting'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at hardcorequesting.common.fabric.proxies.CommonProxy.init(CommonProxy.java:12) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at hardcorequesting.common.fabric.HardcoreQuestingCore.initialize(HardcoreQuestingCore.java:61) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at hardcorequesting.fabric.HardcoreQuestingFabric.onInitialize(HardcoreQuestingFabric.java:83) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at hardcorequesting.common.fabric.proxies.CommonProxy.init(CommonProxy.java:12) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at hardcorequesting.common.fabric.HardcoreQuestingCore.initialize(HardcoreQuestingCore.java:61) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at hardcorequesting.fabric.HardcoreQuestingFabric.onInitialize(HardcoreQuestingFabric.java:83) ~[HQM-1.16.4+5.5.8-fabric.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```

**Comment by kirderf1** [comment]
Looks like #557 was incomplete and only sufficient for the classloader used by forge, but not for the one used by fabric.
