### ISSUE TITLE
reward crashes the game (1.17.1 fabric)

### ISSUE THREAD

**Issue by Chuunkyz** [lorddusk/HQM#598]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 9/9/21, 3:56 PM
Description: Rendering screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (hardcorequesting.common.fabric.client.interfaces.GuiBase) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by the screen not calling super.init(Lnet/minecraft/client/MinecraftClient;II)V
	at net.minecraft.class_437.ensureEventsAreInitialised(class_437.java:3823)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:3846)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:128)
	at net.minecraft.class_757.handler$zpa000$onBeforeRenderScreen(class_757.java:3538)
	at net.minecraft.class_757.handler$ghl000$onBeforeRenderScreen(class_757.java:13020)
	at net.minecraft.class_757.method_3192(class_757.java:1272)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialised(class_437.java:3823)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:3846)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$elk000$fillPatchouliContext(class_128.java:1021)
	at net.minecraft.class_128.<init>(class_128.java:48)
	at net.minecraft.class_128.method_560(class_128.java:342)
	at net.minecraft.class_757.method_3192(class_757.java:1276)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Screen render details --
Details:
	Screen name: hardcorequesting.common.fabric.client.interfaces.GuiReward
	Mouse location: Scaled: (252, 151). Absolute: (1011.000000, 605.000000)
	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Chuunkyz__'/302, l='ClientLevel', x=-86.91, y=69.00, z=681.27]]
	Chunk stats: 1369, 1023
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,69,-112), Section: (at 0,5,0 in -15,4,-7; chunk contains blocks -240,-64,-112 to -225,319,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 41140 game time, 26050 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

**Comment by canitzp** [comment]
oh no @kirderf1 pls fix

**Comment by Chuunkyz** [comment]
thanx for fast reply
can i make my quest rewards before the version is released ? so i can release the new version of my pack immediately after the new release ?

**Comment by kirderf1** [comment]
This should not have anything to do with how quests are stored, so you should be fine creating quest rewards.

**Comment by kirderf1** [comment]
Had no trouble replicating the issue in a dev environment. Should not take long to figure out what needs to be done.
