### ISSUE TITLE
server crash, latest 1.17.1 fabric

### ISSUE THREAD

**Issue by Chuunkyz** [lorddusk/HQM#603]
Description: Exception in server tick loop

java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at hardcorequesting.common.fabric.quests.QuestingDataManager$State.loadFromString(QuestingDataManager.java:129)
	at java.util.Optional.ifPresent(Optional.java:178)
	at hardcorequesting.common.fabric.quests.SimpleSerializable.load(SimpleSerializable.java:36)
	at hardcorequesting.common.fabric.quests.QuestLine.loadAll(QuestLine.java:183)
	at hardcorequesting.common.fabric.event.WorldEventListener.onLoad(WorldEventListener.java:18)
	at me.shedaniel.cloth.api.common.events.v1.WorldLoadCallback.lambda$static$0(WorldLoadCallback.java:39)
	at net.minecraft.server.world.ServerWorld.handler$zoc000$init(ServerWorld:4594)
	at net.minecraft.server.world.ServerWorld.<init>(ServerWorld:224)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer:383)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:350)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer:184)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

**Comment by canitzp** [comment]
Your HQM quest files are invalid, like the actuall text in these files doesn't fit to the standard HQM needs to read it.
Please make sure all the quest files are valid .json format. There are tester on the internet, where you can check them easily.

**Comment by kirderf1** [comment]
In particular, it is the state.json file that it has trouble reading

**Comment by kirderf1** [comment]
Assuming it's not done already, we should probably be catching the exception and rethrowing it with the name of the affected file in the error message

**Comment by Chuunkyz** [comment]
the thing is, that i deleted the config file to test again.
it works on singleplayer, but still crashes on server. Seems like it's not a problem with my quests.

**Comment by kirderf1** [comment]
This has to do with the data file state.json located in the world folder, and not any of the config files.

**Comment by Chuunkyz** [comment]
okay, where can i verify my quests ?

**Comment by kirderf1** [comment]
https://jsonlint.com/ should work for what canitzp described.
But again, it is primarily state.json in the world folder that you should be looking at.
