### ISSUE TITLE
load doesn't like big icons

### ISSUE THREAD

**Issue by Katrix-** [lorddusk/HQM#64]
Any questline with big icons will fail to load correctly.

This loads fine:
```json
{
  "name": "Big Icon",
  "quests": [
    {
      "name": "Quest",
      "x": 24,
      "y": 19
    }
  ],
  "reputation": []
}
```

This does not:

```json
{
  "name": "Big Icon",
  "quests": [
    {
      "name": "Quest",
      "x": 24,
      "y": 19,
      "bigIcon": true
    }
  ],
  "reputation": []
}
```

Error message:
```java
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 8 column 22
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:815)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.commands.CommandLoad.loadSet(CommandLoad.java:87)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.commands.CommandLoad.handleCommand(CommandLoad.java:61)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.commands.CommandHandler.func_71515_b(CommandHandler.java:93)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 8 column 22
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.parsing.QuestAdapter$10.read(QuestAdapter.java:688)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.parsing.QuestAdapter$10.read(QuestAdapter.java:582)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.parsing.QuestAdapter$11.read(QuestAdapter.java:872)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at hardcorequesting.parsing.QuestAdapter$11.read(QuestAdapter.java:826)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[20:55:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 15 more
```

Tried on 4.3.3 and 4.4.0

**Comment by hilburn** [comment]
Yeah that's my bad - I derped. Fixed it though
