### ISSUE TITLE
[1.18.2 FABRIC] can not save existing worlds

### ISSUE THREAD

**Issue by MSandro** [lorddusk/HQM#656]
MC is stuck at Saving World 
```
[11:25:06] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3760()" because the return value of "hardcorequesting.common.fabric.HardcoreQuestingCore.getServer()" is null
	at hardcorequesting.common.fabric.network.NetworkManager.sendToAllPlayers(NetworkManager.java:111) ~[HQM-1.18.2-5.10.1-fabric.jar:?]
	at hardcorequesting.common.fabric.death.DeathStatsManager.resync(DeathStatsManager.java:60) ~[HQM-1.18.2-5.10.1-fabric.jar:?]
	at hardcorequesting.common.fabric.event.PlayerTracker.onPlayerLogin(PlayerTracker.java:35) ~[HQM-1.18.2-5.10.1-fabric.jar:?]
	at hardcorequesting.common.fabric.HardcoreQuestingCore.lambda$initialize$2(HardcoreQuestingCore.java:74) ~[HQM-1.18.2-5.10.1-fabric.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.2.50.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.2.50.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
	at jdk.proxy2.$Proxy140.join(Unknown Source) ~[?:?]
	at net.minecraft.class_3324.handler$zge000$placeNewPlayer(class_3324.java:1466) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$bpb000$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by kirderf1** [comment]
That's an odd one. I'm not getting this issue in either singleplayer or multiplayer. Do you have any further details on the issue? How consistently does it happen? Under which circumstances did that happen? Which versions of architectury-api and fabric-api are you using?

**Comment by canitzp** [comment]
Since there was no answer, this issue is closed now.
