### ISSUE TITLE
Client crash when deleting everything on a page

### ISSUE THREAD

**Issue by MysticcX** [lorddusk/HQM#669]
When trying to delete the last thing on certain pages the client ends up crashing.

**Loaded on Fabric**:
**ModLoader** v0.14.10
**FabricAPI** v0.64.0
**Minecraft** 1.19.2
**Mod Version** 5.12.2

**Crash Report**:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-11-13 19:32:05
Description: mouseClicked event handler

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at hardcorequesting.common.fabric.client.interfaces.graphic.EditBagsGraphic.onClick(EditBagsGraphic.java:205)
	at hardcorequesting.common.fabric.client.interfaces.GuiQuestBook.method_25402(GuiQuestBook.java:260)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Detailed Crash Report (via pastebin)**:

**[Crash Report](https://pastebin.com/X8j8Gncs)**

**Comment by MysticcX** [comment]
Happened while messing with reputation pages but also continued to crash on the quest pages when adding aspects such as the quest type along with other inputs

**Comment by kirderf1** [comment]
The crashlog was for a bag menu specific problem. I tested around a little with the reputation menu without finding anything, so if there's an issue left after fixing this specific crash, I recommend up new issues for any other problems.
