### ISSUE TITLE
[1.18.2] Item Search is Blank

### ISSUE THREAD

**Issue by Cazadorsniper** [lorddusk/HQM#688]
Version: HQM-1.18.2-5.11.3-forge
When searching up anything in HQM this pops up in the log:

`[Render thread/ERROR]: Item search failed with error: 
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/MessageSupplier
	at net.minecraftforge.eventbus.EventBus.handleException(EventBus.java:316) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:307) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275) ~[forge-1.18.2-40.2.14-universal.jar%23347!/:?]
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768) ~[client-1.18.2-20220404.173914-srg.jar%23342!/:?]
	at hardcorequesting.common.forge.client.TextSearch.initItems(TextSearch.java:86) ~[HQM-1.18.2-5.11.3-forge.jar%23185!/:?]
	at hardcorequesting.common.forge.client.TextSearch.doSearch(TextSearch.java:66) ~[HQM-1.18.2-5.11.3-forge.jar%23185!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by kirderf1** [comment]
My guess is that this problem is the same as was fixed by https://github.com/lorddusk/HQM/pull/673 in the 1.19 version of this mod. I'd assume that it could be backported to 1.18 if someone would be up for making that update.

**Comment by canitzp** [comment]
Sorry but 1.18.1 is not a generally supported version and it never was

**Comment by Cazadorsniper** [comment]
This was for 1.18.2 but ok I worked around it.
